name: searching_algoritm
description: A Dart package providing various search algorithms including Binary Search, Linear Search, and Jump Search.
version: 1.0.1
repository: https://github.com/Aabdulloh2005/searching_algoritm.git

environment:
  sdk: '>=3.3.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
